version: '3.8'
services:
    db:
        container_name: mysql_college
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: admin
            MYSQL_DATABASE: sharing_is_caring
        ports:
            - 8001:3306
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - '8002:80'
        restart: always
        environment:
            PMA_HOST: db
        depends_on:
            - db
    php-apache-environment:
        container_name: college-web-php
        image: php:8.0-apache
        ports:
            - 3000:8000
        depends_on:
            - db
